App_Order/urls.py
from django.urls import path
from App_Order import views


app_name="App_Order"

urlpatterns = [

    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name="cart"),
    path('itemRemove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase_item/<pk>/', views.increase_cart, name="increase"),
     path('decrease_item/<pk>/', views.decrease_cart, name="decrease"),
   
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name="App_Shop"

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('details/<pk>/', views.Product_Details.as_view(), name='details'),
    path('category/', views.Category.as_view(), name='category'),
    path('showCategoryWise/<pk>/', views.show_Category_Wise, name='showCategoryWise'),
    
   

]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('home/', include('App_Shop.urls')),
    path('Shop/', include('App_Order.urls')),
    path('', views.index , name='index'),
    path('payment/', include('App_payment.urls')),
    path('search/', views.search_product, name='search'),
    
    

]


urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from statistics import mode
from unicodedata import category
from django.db import models

# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category', default=True, null=False)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    preview_text = models.TextField(max_length=1000, verbose_name='Discription')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]

App_Shop/views.py
from unicodedata import category
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from App_Shop.models import Product
from App_Shop.models import Category

# Create your views here.


class Home(ListView):
    model= Product
    template_name='App_Shop/home.html'

class Product_Details(DetailView):
    model= Product
    template_name='App_Shop/product_details.html'

class Category(ListView):
    model= Category
    template_name='App_Shop/category_list.html'

    
def show_Category_Wise(request,pk):
    object_list=Product.objects.filter(category=pk)
    return render(request,'App_Shop/show_category_wise.html', context={'object_list':object_list})

  

templates/App_Shop/category_list.html
{% extends 'base.html' %}
{% block body_block %}
{% for categories in object_list %}


<h4 class="title"><a href="{% url 'App_Shop:showCategoryWise' pk=categories.pk %}"><b>{{categories.title}}</b></a></h4>

{% endfor %}

{% endblock %}

templates/App_Shop/home.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container my-5">
    
    <div class="row">
      {% for product in object_list %}
      <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
          <div class="img-wrap">
            <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </div>
          <figcaption class="info-wrap">
            <h4 class="title"><a href="{% url 'App_Shop:details' pk=product.pk %}"><b>{{product.name}}</b></a></h4>
            <div class="action-wrap">
              <div class="price-wrap h5">
                <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
              </div>
            </div>
          </figcaption>
        </figure>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/App_Shop/product_details.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-4">
  <div class="card">
    <div class="row">
      <aside >
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
                <a href="#"><img src="/media/{{object.mainimage}}" style="width:400px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body ">
          <h3 class="title mp-3"> <b>{{object.name}}</b></h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.preview_text|linebreaks}}</p>
            </dd>
          </dl>
          <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}

templates/App_Shop/show_category_wise.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container my-5">
    
    <div class="row">
      {% for product in object_list %}
      <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
          <div class="img-wrap">
            <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </div>
          <figcaption class="info-wrap">
            <h4 class="title"><a href="{% url 'App_Shop:details' pk=product.pk %}"><b>{{product.name}}</b></a></h4>
            <div class="action-wrap">
              <div class="price-wrap h5">
                <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
              </div>
            </div>
          </figcaption>
        </figure>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}